# Generated by Django 3.0 on 2021-05-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, null=True, unique=True)),
                ('projectHeading', models.CharField(max_length=100, null=True, unique=True)),
                ('projectTagline', models.CharField(max_length=100, null=True, unique=True)),
                ('projectName', models.CharField(max_length=50, null=True, unique=True)),
                ('projectMeta', models.CharField(max_length=250, null=True, unique=True)),
                ('projectDescription', models.TextField(max_length=500, null=True)),
                ('projectThumpnailImage', models.FileField(null=True, upload_to='Images/Project/Thumpnails/')),
                ('projectDetailsImage', models.FileField(null=True, upload_to='Images/Project/Details/')),
                ('projectGithub', models.URLField(null=True)),
                ('uploadedDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(max_length=50, null=True)),
                ('techIcon', models.FileField(null=True, upload_to='Icons/Projects/')),
                ('projectName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Projects')),
            ],
            options={
                'verbose_name_plural': 'Project Technologies',
            },
        ),
    ]
