# Generated by Django 3.0 on 2021-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('emailId', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('addedDate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='uploadedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
