# Generated by Django 3.0 on 2021-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210503_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelOfEducation', models.CharField(max_length=50, null=True)),
                ('stream', models.CharField(max_length=100, null=True, unique=True)),
                ('university', models.CharField(max_length=100, null=True, unique=True)),
                ('startedYear', models.CharField(max_length=10, null=True)),
                ('endYear', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Education Qualifications',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('companyName', models.CharField(max_length=50, null=True, unique=True)),
                ('startedYear', models.DateField()),
            ],
        ),
    ]
