# Generated by Django 3.0 on 2021-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutme_education_experiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50, null=True)),
                ('cource', models.CharField(max_length=100, null=True)),
                ('certificateNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('certififedYear', models.DateField()),
                ('certififcationExpiry', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.AlterModelOptions(
            name='experiences',
            options={'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AddField(
            model_name='experiences',
            name='endYear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='presentWorking',
            field=models.BooleanField(default=True),
        ),
    ]
