# Generated by Django 3.0 on 2021-05-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210503_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certififcationExpiry',
            field=models.DateField(null=True),
        ),
    ]
