# Generated by Django 3.0 on 2021-05-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210503_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certififcationExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='endYear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
