# Generated by Django 3.0 on 2021-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certififedYear',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cource',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
