# Generated by Django 3.0 on 2021-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='bannerImage',
            field=models.FileField(blank=True, null=True, upload_to='Static-Images/'),
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
