# Generated by Django 3.0 on 2021-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210507_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50, null=True)),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
                ('uploadDate', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Resume',
            },
        ),
    ]
